# Generated by Django 4.2.4 on 2023-08-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_todo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
